### PR TITLE
Add support for .NET 4.5 (fixes #3)

### LINKED ISSUE #3: Support .NET 4.5
Ya, I know it's out of support as of Jan 2016, but folks still use it.  No behavioral changes required, just additional targets and a new set of packages.  PR shortly...

### PR DESCRIPTION
**Pull request by strvmarv**

### CODE REVIEW

**Comment by lecaillon** [comment]
The 4.5.1 is already unssuported. So add another one, not fan ? 
What about replace the 4.5.1 by the 4.5 and add the actual 4.6 and 4.7 ?

**Review by lecaillon — CHANGES_REQUESTED** [review]
Replace the net452 by the net45 and add the net46 and net47

**Comment by strvmarv** [comment]
Better?  It can be helpful to consumers to support 4.5.1 and 4.5.2 explicitly.  Also note that with 4.7.1 you might as well jump to .NET Core 2.0.  I'm just looking for .NET 4.5 support myself...at this point...

**Comment by lecaillon** [comment]
In wich way it can be helpfull ? They can use the 4.5 version in their 4.5.2 project for example. And with the netstandard 1.3 thay can already target .NET Core 2.0
Isn't it ?

**Comment by strvmarv** [comment]
I'm ok with this change-set as-is if you are...don't want to "scope-creep" too much here...

http://immo.landwerth.net/netstandard-versions/

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Review by lecaillon — APPROVED** [review]

**Comment by strvmarv** [comment]
Thanks!

**Pull request merged**
