### PR TITLE
Feature/Numerics

### PR DESCRIPTION
**Pull request by strvmarv**
* Re-work Positive into single generic constrainted call
* Add Negative and Zero in similar implementation

### CODE REVIEW

**Comment by strvmarv** [comment]
Simplified numeric checks and added Negative and Zero...

**Comment by lecaillon** [comment]
Great thank you !
With some unit tests (I can help you with some if you want) it will be perfect.
I look more closely when I can.

**Review by lecaillon — CHANGES_REQUESTED** [review]
Add some unit tests

**Comment by strvmarv** [comment]
Ack, sorry, will do...

**Comment by lecaillon** [comment]
Awsome, thanks again !

**Pull request merged**
